### PR TITLE
WIP(?) Cloud.gov manifests

### PR DESCRIPTION
**Pull request by cmc333333**
We still need to hammer out these standards, but this is a starting point for generating cloud.gov files.

It also refactors the shared languages prompts and proposes a "TODO" management system.

Ready for feedback now -- we can incorporate into this branch or open a new PR.

### CODE REVIEW

**Comment by msecret** [comment]
I like the shared config idea a lot. When Yoz and I were pairing, we found there were many prompts, such as project name, that would have to be shared with a bunch of different generators.

**Review by msecret — APPROVED** [review]

**Comment by LinuxBozo** [comment]
Can we consolidate the `Procfile` to a single master version to keep things DRY? Also, maybe it makes sense to ask if there will be a worker process, and command for that worker if so?

**Comment by cmc333333** [comment]
@LinuxBozo that makes sense and gets us generating manifests (which was the original goal). Quick question on deduplication: is it reasonable for Ruby projects to have a `Procfile`?

**Comment by LinuxBozo** [comment]
@cmc333333 yessir. https://devcenter.heroku.com/articles/getting-started-with-rails5#procfile

**Comment by cmc333333** [comment]
:+1: will do. I'll merge this as is to clean up #51's diff, but will follow up with those changes

**Pull request merged**
